name: MSBuild

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: R3nzSkin.sln
  BUILD_CONFIGURATION: RiotGamesServers

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Platform=x64 /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
