name: MSBuild

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: R3nzSkin.sln

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Riot-SSE2, Riot-AVX2, China-SSE2, China-AVX2]

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Platform=x64 /p:Configuration=${{matrix.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: 'Release/${{matrix.BUILD_CONFIGURATION}}'
        filename: '../../R3nzSkin-${{matrix.BUILD_CONFIGURATION}}.zip'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'R3nzSkin-${{matrix.BUILD_CONFIGURATION}}.zip'
        allowUpdates: true
        
